### ISSUE TITLE
最初のアニメーションが遅い気がする

### ISSUE THREAD

**Issue by phelrine** [ackyla/lb#26]
現在地にいくまでのアニメーションいらなさそう.
ロードされた時に現在地にいってほしい.

**Comment by phelrine** [comment]
地図非表示の時にLoadingアニメーションとかがあるといいですね.

**Comment by ackyla** [comment]
ぐーぐるまっぷはアニメーションないしいらないのでは

**Comment by phelrine** [comment]
たしかに問題なさそうです.
でも, 通信環境が悪い場所だとなかなか表示されなかったのでアプリ内での通信中はなんらかの表示を入れたほうがよさそうです.

**Comment by ackyla** [comment]
なるほど
