### ISSUE TITLE
アバター設定したい

### ISSUE THREAD

**Issue by ackyla** [ackyla/lb#28]

**Comment by phelrine** [comment]
ユーザーのですか？

**Comment by ackyla** [comment]
はい
public以下においておいたらいいかな

**Comment by phelrine** [comment]
デフォルトアバターですか？

**Comment by ackyla** [comment]
できたらアップロードしたいけど
作るのめんどい

**Comment by ackyla** [comment]
改善の余地ありあり
現状アップロードしたらアプリ再起動するか
陣力消費するとかでユーザー情報更新すると新しいのに変わる

**Comment by ackyla** [comment]
再起動しないとだめぽ

**Comment by ackyla** [comment]
![hoge](https://f.cloud.github.com/assets/535404/1893346/2f8bb008-7a87-11e3-9af6-3820f872f839.png)
