### ISSUE TITLE
マップ画面に各テリトリーに移動するボタンがほしい

### ISSUE THREAD

**Issue by phelrine** [ackyla/lb#34]
いちいちテリトリ一覧に戻りたくない.

**Comment by ackyla** [comment]
イメージわかない
テリトリータブ→テリトリー選択→詳細画面→見る→マップ
を
テリトリータブ→テリトリー選択→マップ
にはしたい感じ

**Comment by phelrine** [comment]
Latitudeのユーザーみたいな感じです.
マップに←→みたいなボタンがあって押すと各ユーザーに移動する感じです.
