### ISSUE TITLE
特定の機種で設定ボタンが表示されない

### ISSUE THREAD

**Issue by phelrine** [ackyla/lb#42]
Galaxy Note 2だと設定ボタンが表示できません.

**Comment by ackyla** [comment]
ゲーム画面？
タイトル画面は表示されてる？(最新版で)

**Comment by phelrine** [comment]
タイトルでもでてないですね.
上の黒い部分ですよね?

**Comment by ackyla** [comment]
はい
タイトルはデバッグモードのときだけ表示される

**Comment by phelrine** [comment]
debug_mode trueの状態で表示されていません.
あとlocal_value.sampleで<boolean name=debug_mode>になっていたんですが, boolじゃないとコンパイル通りませんでした.

**Comment by ackyla** [comment]
直し忘れなのでコミットしておいて下さい

**Comment by phelrine** [comment]
直しました.
af492c8394ebd82c9c3136d076074c37c68e37c7

**Comment by ackyla** [comment]
エミュレータで再現しなーい
スペック詳細教えてくれ
あとスクリーンショットとれたらそれも

**Comment by phelrine** [comment]
どのあたりの情報を載せればいいですか?
SSは以下です.
![screenshot_2014-01-09-00-35-39](https://f.cloud.github.com/assets/61105/1869480/28cf134e-787b-11e3-97ec-417102a6048c.png)
![screenshot_2014-01-09-00-36-08](https://f.cloud.github.com/assets/61105/1869481/28d529b4-787b-11e3-9995-a16cdb39081b.png)

**Comment by ackyla** [comment]
ほんとだ

画面解像度とandroidのバージョンあたり

**Comment by phelrine** [comment]
画面解像度はHD(720×1280)
バージョンはandroid4.1.1です。

**Comment by phelrine** [comment]
なおってました.
