### ISSUE TITLE
画面の表示が崩れる

### ISSUE THREAD

**Issue by phelrine** [ackyla/lb#44]
陣力の表示がおかしいです.

![screenshot_2014-01-09-11-51-38](https://f.cloud.github.com/assets/61105/1874709/441346a8-78d9-11e3-88c9-c080ab718976.png)

**Comment by ackyla** [comment]
うまくいけばこうなる
![screen shot 2014-01-09 at 11 19 19 pm](https://f.cloud.github.com/assets/535404/1878294/22f5b50e-7939-11e3-80c0-d6e197b6b65a.png)

**Comment by ackyla** [comment]
なおったらしいので
